# for 迴圈說明：
# for loop explanation:
# for 迴圈用來重複執行一段程式碼，通常用來依序取得序列（如 list、字串、range 產生的數列）中的每個元素。
# The for loop is used to repeatedly execute a block of code, usually to access each element in a sequence
# (such as a list, string, or a sequence generated by range).
# for迴圈不包含結尾的數字，範圍是從起始數字到結束數字的前一個數字。
# The for loop does not include the ending number; the range is from the starting number to
# 基本語法：
# Basic syntax:
# for 變數 in 可迭代物件:
# for variable in iterable:
# 要重複執行的程式區塊
# code block to repeat
# 例如：for i in range(5): 會讓 i 依序取得 0, 1, 2, 3, 4
# Example: for i in range(5): will let i take the values 0, 1, 2, 3, 4 in order.

# 範例1：range(5) 會產生 0~4 的整數
# Example 1: range(5) generates integers from 0 to 4
for i in range(5):
    print(i)  # 輸出 0, 1, 2, 3, 4
    # Output: 0, 1, 2, 3, 4

# 範例2：range(1, 10) 會產生 1~9 的整數
# Example 2: range(1, 10) generates integers from 1 to 9
for i in range(1, 10):
    print(i)  # 輸出 1, 2, ..., 9
    # Output: 1, 2, ..., 9

# 範例3：range(1, 10, 2) 會產生 1~9 的奇數（相差為2）
# Example 3: range(1, 10, 2) generates odd numbers from 1 to 9 (step is 2)
for i in range(1, 10, 2):
    print(i)  # 輸出 1, 3, 5, 7, 9
    # Output: 1, 3, 5, 7, 9

# 範例4：for 迴圈搭配 list
# Example 4: for loop with a list
fruits = ["apple", "banana", "cherry"]
for fruit in fruits:
    print(fruit)  # 依序輸出 apple, banana, cherry
    # Output: apple, banana, cherry
